env:
  es6: true
  node: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:react/recommended'
  - 'prettier'
  - 'prettier/@typescript-eslint'
plugins:
  - deprecation
  - react
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2018
  project: './tsconfig.eslint.json'
rules:
  '@typescript-eslint/no-parameter-properties': off
  'deprecation/deprecation': warn
  'react/prop-types': 'off'
settings:
  react:
    version: 'latest'
