[build]
  publish = "out"
  command = "npm run export"

[[redirects]]
  from = "/index.html"
  to = "https://amplience.com/blog"
  status = 301
  force = true  

[[redirects]]
  from = "/"
  to = "https://amplience.com/blog"
  status = 301
  force = true
  
[[redirects]]
  from = "/blog/*"
  to = "https://amplience.com/blog/:splat"
  status = 301
  force = true
