[build]
  publish = "out"
  command = "npm run export"

# http and https need separate rules if you don’t force_ssl!
http://blog.yoursite.com/* https://www.yoursite.com/blog/:splat 301!
https://blog.yoursite.com/* https://www.yoursite.com/blog/:splat 301!

[[redirects]]

  from = ""
  to = "https://amplience.com/blog"
  status = 301
  force = false
  query = {path = ":path"}

  from = "/blog/*"
  to = "https://amplience.com/blog/:splat"
  status = 301
  force = false
  query = {path = ":path"}
