[build]
  publish = "out"
  command = "npm run export"

[[redirects]]

  from = "https://productblog-uat-prod.netlify.app"
  to = "https://amplience.com/blog"

  from = "/blog/*"
  to = "https://amplience.com/blog/:splat"
