[build]
  publish = "out"
  command = "npm run export"

[[redirects]]

  from = "/index.html"
  to = "https://amplience.com/blog"

[[redirects]]

  from = "/blog/*"
  to = "https://amplience.com/blog/:splat"
