[build]
  publish = "out"
  command = "npm run export"

[[redirects]]
  from = "https://productblog.amplience.com/index.html"
  to = "https://amplience.com/blog"
  status = 301
  force = true

[[redirects]]
  from = "https://productblog.amplience.com/"
  to = "https://amplience.com/blog"
  status = 301
  force = true
  
[[redirects]]
  from = "https://productblog.amplience.com/blog/*"
  to = "https://amplience.com/blog/:splat"
  status = 301
  force = true
